---
abstract: 'Adapter for Data::Semantic objects'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Value-SemanticAdapter
provides:
  Class::Value::SemanticAdapter:
    file: lib/Class/Value/SemanticAdapter.pm
    version: 1.100841
requires:
  Carp: 0
  Class::Value: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  UNIVERSAL::require: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Value-SemanticAdapter
  homepage: http://search.cpan.org/dist/Class-Value-SemanticAdapter/
  repository: http://github.com/hanekomu/Class-Value-SemanticAdapter
version: 1.100841
